FROM python:latest 

COPY . /app

WORKDIR /app

CMD ["python", "mascaradados.py"]

#docker build -t mascarar-dados .
#docker run -it --name mascarar-dados-container mascarar-dados
#docker start -ai mascarar-dados-container