FROM python:latest 

COPY . /app

WORKDIR /app

CMD ["python", "carguru.py"]

# docker build -t carguru-image .
# docker run  --name carguru-container carguru-image
# docker start -ai carguru-container